package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 11, 2023, 2:55:47 PM by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Districts generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Districts implements java.io.Serializable {

	private Integer id;
	@JsonIgnore private Provinces provinces;
	private int code;
	private String nameInThai;
	private String nameInEnglish;
	@JsonIgnore private Set stores = new HashSet(0);
	@JsonIgnore private Set subdistrictses = new HashSet(0);

	public Districts() {
	}

	public Districts(Provinces provinces, int code, String nameInThai, String nameInEnglish) {
		this.provinces = provinces;
		this.code = code;
		this.nameInThai = nameInThai;
		this.nameInEnglish = nameInEnglish;
	}

	public Districts(Provinces provinces, int code, String nameInThai, String nameInEnglish, Set stores,
			Set subdistrictses) {
		this.provinces = provinces;
		this.code = code;
		this.nameInThai = nameInThai;
		this.nameInEnglish = nameInEnglish;
		this.stores = stores;
		this.subdistrictses = subdistrictses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Provinces getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Provinces provinces) {
		this.provinces = provinces;
	}

	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getNameInThai() {
		return this.nameInThai;
	}

	public void setNameInThai(String nameInThai) {
		this.nameInThai = nameInThai;
	}

	public String getNameInEnglish() {
		return this.nameInEnglish;
	}

	public void setNameInEnglish(String nameInEnglish) {
		this.nameInEnglish = nameInEnglish;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

	public Set getSubdistrictses() {
		return this.subdistrictses;
	}

	public void setSubdistrictses(Set subdistrictses) {
		this.subdistrictses = subdistrictses;
	}

}
