package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 11, 2023, 2:55:47 PM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Favourite generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Favourite implements java.io.Serializable {

	private String favouriteId;
	private Store store;
	private User user;
	private Timestamp createdate;

	public Favourite() {
	}

	public Favourite(String favouriteId, Store store, User user, Timestamp createdate) {
		this.favouriteId = favouriteId;
		this.store = store;
		this.user = user;
		this.createdate = createdate;
	}

	public String getFavouriteId() {
		return this.favouriteId;
	}

	public void setFavouriteId(String favouriteId) {
		this.favouriteId = favouriteId;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

}
