package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 11, 2023, 2:55:47 PM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Orderitem generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Orderitem implements java.io.Serializable {

	private String orderItemId;
	private Product product;
	private Orders orders;
	private int quantity;
	private Date createdate;
	private Date updatedate;

	public Orderitem() {
	}

	public Orderitem(String orderItemId, Product product, Orders orders, int quantity, Date createdate,
			Date updatedate) {
		this.orderItemId = orderItemId;
		this.product = product;
		this.orders = orders;
		this.quantity = quantity;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	public String getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(String orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

}
