package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 10, 2023, 1:16:06 AM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Orderitem generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Orderitem implements java.io.Serializable {

	private String orderItemId;
	private Product product;
	private Orders orders;
	private int quantity;
	private Timestamp createdate;
	private Timestamp updatedate;

	public Orderitem() {
	}

	public Orderitem(String orderItemId, Product product, Orders orders, int quantity, Timestamp createdate,
			Timestamp updatedate) {
		this.orderItemId = orderItemId;
		this.product = product;
		this.orders = orders;
		this.quantity = quantity;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	public String getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(String orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	public Timestamp getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Timestamp updatedate) {
		this.updatedate = updatedate;
	}

}
