package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 10, 2023, 1:16:06 AM by Hibernate Tools 6.1.7.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Product generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Product implements java.io.Serializable {

	private String productId;
	private Store store;
	private Type type;
	private String name;
	private String description;
	private Timestamp expiryDate;
	private BigDecimal price;
	private BigDecimal discountPrice;
	private int quantityAvailable;
	private String imgProduct;
	private Timestamp createdate;
	private Timestamp updatedate;
	@JsonIgnore private Set orderitems = new HashSet(0);

	public Product() {
	}

	public Product(String productId, Store store, Type type, String name, String description, Timestamp expiryDate,
			BigDecimal price, BigDecimal discountPrice, int quantityAvailable, String imgProduct, Timestamp createdate,
			Timestamp updatedate) {
		this.productId = productId;
		this.store = store;
		this.type = type;
		this.name = name;
		this.description = description;
		this.expiryDate = expiryDate;
		this.price = price;
		this.discountPrice = discountPrice;
		this.quantityAvailable = quantityAvailable;
		this.imgProduct = imgProduct;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	public Product(String productId, Store store, Type type, String name, String description, Timestamp expiryDate,
			BigDecimal price, BigDecimal discountPrice, int quantityAvailable, String imgProduct, Timestamp createdate,
			Timestamp updatedate, Set orderitems) {
		this.productId = productId;
		this.store = store;
		this.type = type;
		this.name = name;
		this.description = description;
		this.expiryDate = expiryDate;
		this.price = price;
		this.discountPrice = discountPrice;
		this.quantityAvailable = quantityAvailable;
		this.imgProduct = imgProduct;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.orderitems = orderitems;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Timestamp expiryDate) {
		this.expiryDate = expiryDate;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(BigDecimal discountPrice) {
		this.discountPrice = discountPrice;
	}

	public int getQuantityAvailable() {
		return this.quantityAvailable;
	}

	public void setQuantityAvailable(int quantityAvailable) {
		this.quantityAvailable = quantityAvailable;
	}

	public String getImgProduct() {
		return this.imgProduct;
	}

	public void setImgProduct(String imgProduct) {
		this.imgProduct = imgProduct;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	public Timestamp getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Timestamp updatedate) {
		this.updatedate = updatedate;
	}

	public Set getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set orderitems) {
		this.orderitems = orderitems;
	}

}
