package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 10, 2023, 7:19:20 PM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Review generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Review implements java.io.Serializable {

	private String reviewId;
	private Store store;
	private User user;
	private int rating;
	private String comment;
	private Timestamp createdate;

	public Review() {
	}

	public Review(String reviewId, Store store, User user, int rating, Timestamp createdate) {
		this.reviewId = reviewId;
		this.store = store;
		this.user = user;
		this.rating = rating;
		this.createdate = createdate;
	}

	public Review(String reviewId, Store store, User user, int rating, String comment, Timestamp createdate) {
		this.reviewId = reviewId;
		this.store = store;
		this.user = user;
		this.rating = rating;
		this.comment = comment;
		this.createdate = createdate;
	}

	public String getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(String reviewId) {
		this.reviewId = reviewId;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

}
