package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 14, 2023, 12:18:28 AM by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Type generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Type implements java.io.Serializable {

	private Integer typeId;
	private String typeName;
	private String img;
	@JsonIgnore private Set products = new HashSet(0);

	public Type() {
	}

	public Type(String typeName, String img) {
		this.typeName = typeName;
		this.img = img;
	}

	public Type(String typeName, String img, Set products) {
		this.typeName = typeName;
		this.img = img;
		this.products = products;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
