package th.ac.ku.kps.eng.cpe.model;
// Generated Oct 10, 2023, 1:16:06 AM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * User generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class User implements java.io.Serializable {

	private String userId;
	private String firstname;
	private String lastname;
	private int password;
	private String role;
	private Timestamp lastLoginTimestamp;
	private boolean accountLockStatus;
	private int attemptLogin;
	private Timestamp attemptTimeLogin;
	private boolean twoFactorAuthenticationEnabled;
	private String codeTwoFactorAuthentication;
	@JsonIgnore private Set reviews = new HashSet(0);
	@JsonIgnore private Set orderses = new HashSet(0);
	@JsonIgnore private Set favourites = new HashSet(0);
	@JsonIgnore private Set stores = new HashSet(0);

	public User() {
	}

	public User(String userId, String firstname, String lastname, int password, String role,
			Timestamp lastLoginTimestamp, boolean accountLockStatus, int attemptLogin, Timestamp attemptTimeLogin,
			boolean twoFactorAuthenticationEnabled, String codeTwoFactorAuthentication) {
		this.userId = userId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.password = password;
		this.role = role;
		this.lastLoginTimestamp = lastLoginTimestamp;
		this.accountLockStatus = accountLockStatus;
		this.attemptLogin = attemptLogin;
		this.attemptTimeLogin = attemptTimeLogin;
		this.twoFactorAuthenticationEnabled = twoFactorAuthenticationEnabled;
		this.codeTwoFactorAuthentication = codeTwoFactorAuthentication;
	}

	public User(String userId, String firstname, String lastname, int password, String role,
			Timestamp lastLoginTimestamp, boolean accountLockStatus, int attemptLogin, Timestamp attemptTimeLogin,
			boolean twoFactorAuthenticationEnabled, String codeTwoFactorAuthentication, Set reviews, Set orderses,
			Set favourites, Set stores) {
		this.userId = userId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.password = password;
		this.role = role;
		this.lastLoginTimestamp = lastLoginTimestamp;
		this.accountLockStatus = accountLockStatus;
		this.attemptLogin = attemptLogin;
		this.attemptTimeLogin = attemptTimeLogin;
		this.twoFactorAuthenticationEnabled = twoFactorAuthenticationEnabled;
		this.codeTwoFactorAuthentication = codeTwoFactorAuthentication;
		this.reviews = reviews;
		this.orderses = orderses;
		this.favourites = favourites;
		this.stores = stores;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public int getPassword() {
		return this.password;
	}

	public void setPassword(int password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Timestamp getLastLoginTimestamp() {
		return this.lastLoginTimestamp;
	}

	public void setLastLoginTimestamp(Timestamp lastLoginTimestamp) {
		this.lastLoginTimestamp = lastLoginTimestamp;
	}

	public boolean isAccountLockStatus() {
		return this.accountLockStatus;
	}

	public void setAccountLockStatus(boolean accountLockStatus) {
		this.accountLockStatus = accountLockStatus;
	}

	public int getAttemptLogin() {
		return this.attemptLogin;
	}

	public void setAttemptLogin(int attemptLogin) {
		this.attemptLogin = attemptLogin;
	}

	public Timestamp getAttemptTimeLogin() {
		return this.attemptTimeLogin;
	}

	public void setAttemptTimeLogin(Timestamp attemptTimeLogin) {
		this.attemptTimeLogin = attemptTimeLogin;
	}

	public boolean isTwoFactorAuthenticationEnabled() {
		return this.twoFactorAuthenticationEnabled;
	}

	public void setTwoFactorAuthenticationEnabled(boolean twoFactorAuthenticationEnabled) {
		this.twoFactorAuthenticationEnabled = twoFactorAuthenticationEnabled;
	}

	public String getCodeTwoFactorAuthentication() {
		return this.codeTwoFactorAuthentication;
	}

	public void setCodeTwoFactorAuthentication(String codeTwoFactorAuthentication) {
		this.codeTwoFactorAuthentication = codeTwoFactorAuthentication;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	public Set getFavourites() {
		return this.favourites;
	}

	public void setFavourites(Set favourites) {
		this.favourites = favourites;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

}
